### ISSUE TITLE
ISS: Mismatch-Issues with exceptions on clic pointer fetches

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/core-v-verif#1983] opened 2023-06-19 07:39 UTC
### Type
* Functionally incorrect behavior

### Steps to Reproduce
Please provide:
1. branch: cv32e40s/dev hash: 29653b907e41d691e27e41d0da07211acfce437f
2. Command line
```
make comp_corev-dv gen_corev-dv TEST=corev_rand_instr_obi_err CFG=clic_default USE_ISS=YES COV=YES RUN_INDEX=287 GEN_START_INDEX=287 RNDSEED=399917128 
make test TEST=corev_rand_instr_obi_err CFG=clic_default USE_ISS=YES COV=YES RUN_INDEX=287 GEN_START_INDEX=287 RNDSEED=399917128 
```
3. Logfile:
```
Error (IDV) The reference model is unable to find a legal set of actions to converge to the provided DUT state.
Info (IDV) Reference model mode (HartId: 0):
Info (IDV)   Machine - Machine mode
Info (IDV) Currently applied nets:
Info (IDV)  - irq_id_i => 13
Info (IDV)  - irq_lev_i => c1
Info (IDV)  - irq_sec_i => 3
Info (IDV) Pending net changes:
Info (IDV)  - Group 1:
Info (IDV)  -              irq_i => 1,  age = 15 cycles, 0 retires
Info (IDV)  -           irq_id_i => 11,  age = 15 cycles, 0 retires
Info (IDV)  -          irq_lev_i => 136,  age = 15 cycles, 0 retires
Info (IDV)  -          irq_shv_i => 1,  age = 15 cycles, 0 retires
Info (IDV)  -              irq_i => 0,  age = 13 cycles, 0 retires
Info (IDV)  -           irq_id_i => 0,  age = 13 cycles, 0 retires
Info (IDV)  -          irq_lev_i => 0,  age = 13 cycles, 0 retires
Info (IDV)  -          irq_shv_i => 0,  age = 13 cycles, 0 retires
Info (IDV)  - Group 2:
Info (IDV)  -   InstructionBusFault => 1,  age = 6 cycles, 0 retires
Info (IDV)  -   InstructionBusFault => 0,  age = 0 cycles, 0 retires
Info (IDV) DUT state change (hartId: 0):
Info (IDV)  - dut.pc               - 0x00000000 __jvt_base$+0
Info (IDV)  - dut.x0               - 0x00000000
Info (IDV)  - dut.mstatus          - 0x00001800 SD:0 TW:0 MPRV:0 XS:0(Off) FS:0(Off) MPP:3 VS:0(Off) MPIE:0 UBE:0 MIE:0
Info (IDV)  - dut.mepc             - 0x0001b72c
Info (IDV)  - dut.mcause           - 0x70880018 Interrupt:0 minhv:1 mpp:3 mpie:0 mpil:136 Code:24
Info (IDV)  - dut.mintstatus       - 0x88000000
Info (IDV) Reference state change evaluation tree (HartId: 0):
Info (IDV) No state change found for reference to converge to DUT state.
Warning (IDV) The reference is being forced to converge to the DUT state, results that follow should be treated with caution.
Info (IDV) Updating mstatus from 00000088 to 00001800
Info (IDV) Updating mepc from 00000160 to 0001b72c
Info (IDV) Updating mcause from 30000000 to 70880018
Info (IDV) Updating mintstatus from 00000000 to 88000000
Info (IDV) Instruction executed prior to mismatch '0x0(__jvt_base$+0): 6001b06f j       1b600'
Error (IDV) CSR register value mismatch (HartId:0, PC:0x00000000 __jvt_base$+0):
Info (IDV)  1> CSR fb1 (mintstatus)
Info (IDV)   . dut:0x88000000
Info (IDV)   . ref:0x00000000 mil:0 uil:0
UVM_ERROR @ 1479.300 ns : idvPkg.sv(90) reporter [] uvmt_cv32e40s_tb.imperas_dv.idv_trace2api.state_compare @ 1479.000 ns: MISMATCH
```

### Additional context
DUT takes shv-interrupt with level 136 (0x88), and traps with bus-error on the pointer fetch, leaving minhv set upon entering the exception handler - the ISS is unable to find a valid state that equates to the DUT state and fails.

**Comment by silabs-hfegran** [comment] 2023-06-19 08:03
Note, there has been a change on RVFI signaling with regards to clic-pointer exceptions, as these were not reported leading to missing information. 

Currently, rvfi_valid + rvfi_trap _is_ reported on these exceptions, and there is another helper signal available that identifies this specific case (```rvfi_trap.clicptr```)

**Comment by silabs-hfegran** [comment] 2023-06-19 08:19
My hypothesis is that the converge-to-valid-states logic in the ISS somehow fails to update the mintstatus-csr, as this and a handful of other cases also report that they force-update mintstatus with a new value, but then fails with a mintstatus mismatch immediately afterwards.

**Comment by eroom1966** [comment] 2023-06-19 10:16
Hi Henrik
We are investigating the issue here - I can see what the problem is.
In this instance I think the signal InstructionBusFault, cannot be specific to the face that the fault did not occur on the instruction fetch itself, but on the fetch of the value pointed at by mtvt.
let us discuss this internally and work out the best way to handle this.

**Comment by eroom1966** [comment] 2023-07-18 10:31
@silabs-hfegran 
Apologies for the time taken to fully investigate this issue.
Please pull the updates from ImperasDV-OpenHW, this issue is now fixed on this commit

```
commit 9886954b4a7ca31e611ddb47945e8ba981630ad5 (HEAD -> main, origin/main, origin/HEAD)
Author: eroom1966 <moore@imperas.com>
Date:   Tue Jul 18 11:28:21 2023 +0100

    Fix for sampling of CV32E40S/InstructionBusFault


```

**Comment by silabs-hfegran** [comment] 2023-07-18 10:49
> @silabs-hfegran Apologies for the time taken to fully investigate this issue. Please pull the updates from ImperasDV-OpenHW, this issue is now fixed on this commit
> 
> ```
> commit 9886954b4a7ca31e611ddb47945e8ba981630ad5 (HEAD -> main, origin/main, origin/HEAD)
> Author: eroom1966 <moore@imperas.com>
> Date:   Tue Jul 18 11:28:21 2023 +0100
> 
>     Fix for sampling of CV32E40S/InstructionBusFault
> ```

Thanks for these fixes @eroom1966, I will run them through my regressions

**Comment by eroom1966** [comment] 2023-08-01 10:05
@silabs-hfegran can this be closed ?

**Closed as completed** 2023-08-23 11:57 UTC
Labels: bug, tool, cv32e40s
