### ISSUE TITLE
Step and compare fails if debug_req_i is asserted at the same time as a trigger match

### ISSUE THREAD

**Issue by silabs-oysteink** [openhwgroup/core-v-verif#331] opened 2020-11-05 08:28 UTC
## Bug Title
Step and compare fails if debug_req_i is asserted at the same time as a trigger match

### Component
**Component:Verif**

### Steps to Reproduce
1. Clone https://github.com/silabs-oysteink/core-v-verif
2. Check out the branch silabs-oysteink_debug-cov-update
3. make  test TEST=debug_test USE_ISS=YES

Note that my fork of core-v-verif currently points to my fork of the cv32e40p repo as there is a (not yet PR'ed) change to the tracer to support ebreak instructions at the trigger address.

>   test7.3: Expect Trigger and debug_req_i
UVM_ERROR @ 461124.300 ns : uvmt_cv32_step_compare.sv(96) reporter [Step-and-Compare] dcsr expected=0x400080c3 and actual=0x40008083 PC=0x1a110800

The miscompare translates to RTL using cause=2 (trigger) while the ISS is using cause=3 (haltreq). In a race between these to causes, trigger should win since it has the highest priority.
<img width="1133" alt="trig_haltreq_miscompare" src="https://user-images.githubusercontent.com/66771756/98215622-50490080-1f48-11eb-8212-230fb2a677a1.PNG">

**Comment by MikeOpenHWGroup** [comment] 2020-11-05 13:28
Good catch @silabs-oysteink.  Is the problem in the Reference Model, the tracer, or the step-and-compare logic?   It seems from your last sentence, the issue is with the RM not recognizing that trigger has a higher priority.  However, it could be that the RM doesn't see coincident trigger and halt events.

**Comment by silabs-oysteink** [comment] 2020-11-05 13:31
I think that the issue is within the ISS, Lee is on the case to check it out. There is a secondary issue though, as communicated per e-mail; The code generated by different versions of GCC may break the exact timing for the debug_req and irq from the virtual peripheral.

**Comment by MikeOpenHWGroup** [comment] 2020-11-17 12:56
Hi @silabs-oysteink, @eroom1966, can one or both of you post an update to this issue?   It is important that we resolve this issue this week.

**Comment by silabs-oysteink** [comment] 2020-11-17 13:03
The test "debug_test_trigger" is now passing with ISS enabled, so to my knowledge this issue is fixed. Maybe @eroom1966 can comment on the solution?

**Comment by eroom1966** [comment] 2020-11-17 17:05
yes this apears to be passing

**Comment by MikeOpenHWGroup** [comment] 2020-11-17 17:51
Thanks @silabs-oysteink and @eroom1966.  I will close this issue now.

**Closed by MikeOpenHWGroup** 2020-11-17 17:51 UTC
