### ISSUE TITLE
[cv_dv_utils reset_driver_c] reset_driver does not compile with uvm-1.2

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/core-v-verif#2522] opened 2024-08-08 09:04 UTC
Hello,

In one of the class of the reset_driver_c, the constructor "new" was missing, it did not pose any issues with uvm-1.1d. 
Adding the constructor resolves the issue with uvm-1.2. 

Thanks and regards
Tanuj Khandelwal

**Comment by MikeOpenHWGroup** [comment] 2024-08-08 13:29
Hi @khandelwaltanuj, it is not clear to me what the issue is here and what action we should take.  If you are talking about [cv_dv_utils/uvm/reset_gen/reset_driver_c.svh](https://github.com/openhwgroup/core-v-verif/blob/master/lib/cv_dv_utils/uvm/reset_gen/reset_driver_c.svh), the constructor is implemented [here](https://github.com/openhwgroup/core-v-verif/blob/e06bd577f5db816015ec16a901e6e8f39cf7d640/lib/cv_dv_utils/uvm/reset_gen/reset_driver_c.svh#L121).  Did you mean [dummy_txn](https://github.com/openhwgroup/core-v-verif/blob/e06bd577f5db816015ec16a901e6e8f39cf7d640/lib/cv_dv_utils/uvm/reset_gen/reset_driver_c.svh#L85) or [reset_counter_c](https://github.com/openhwgroup/core-v-verif/blob/e06bd577f5db816015ec16a901e6e8f39cf7d640/lib/cv_dv_utils/uvm/reset_gen/reset_driver_c.svh#L89)?  If so, please create a pull-request to resolve this Issue.

Thanks!

**Comment by khandelwaltanuj** [comment] 2024-08-08 13:32
Hi @MikeOpenHWGroup 

My bad, it did not give the details. It is the reset_counter_c class that poses problem with UVM-1.2. 

Thanks!

**Comment by MikeOpenHWGroup** [comment] 2024-08-08 14:27
Is this Issue resolved in pull-request #2524?

**Comment by MikeOpenHWGroup** [comment] 2024-08-29 14:29
Hi @khandelwaltanuj, is there an update on this issue?

**Comment by khandelwaltanuj** [comment] 2024-10-07 08:34
Hi @MikeOpenHWGroup 

This issue has been fxed normally. 

Regards
Tanuj

**Comment by MikeOpenHWGroup** [comment] 2024-10-07 19:03
Hi @khandelwaltanuj, if that is the case, please add a comment to indicated which PR fixed the problemm and then close this issue.  Thanks.

**Comment by khandelwaltanuj** [comment] 2024-10-09 05:42
Hi @MikeOpenHWGroup

Normally the pull request https://github.com/openhwgroup/core-v-verif/pull/2524 has the fix of this issue.

Regards
Tanuj

**Closed** 2024-10-09 13:38 UTC
Labels: Common Infrastructure
